# Generated by Django 5.2 on 2025-06-08 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: J06.9', max_length=10, unique=True)),
                ('descricao', models.CharField(help_text='Ex: Infecção aguda das vias aéreas superiores', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=100)),
                ('paciente_cpf', models.CharField(max_length=14)),
                ('sintomas', models.TextField()),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('cid_aplicado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacao.cid')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Tratamento para Virose Comum', max_length=200)),
                ('medicamentos', models.TextField(help_text='Liste os medicamentos e suas dosagens. Ex: Dipirona 500mg - 1 comp a cada 6h por 3 dias.')),
                ('orientacoes_gerais', models.TextField(help_text='Ex: Manter repouso, beber bastante líquido.')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='aplicacao.cid')),
            ],
        ),
    ]
