# Generated by Django 5.2 on 2025-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='paciente_idade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente_peso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
