# Generated by Django 5.2 on 2025-06-08 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_consulta_paciente_idade_consulta_paciente_peso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_personalizado', models.CharField(max_length=200)),
                ('medicamentos_personalizados', models.TextField()),
                ('orientacoes_personalizadas', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.cid')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_personalizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
