# Generated by Django 5.2.2 on 2025-06-08 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_receitapersonalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='receita_gerada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacao.receitapersonalizada'),
        ),
    ]
